// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Radio_player.Core.Entities;

namespace Radio_player._Entities.Concrete.DatabaseFirst;

public partial class Radio : IEntity
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int IdRadio { get; set; }

    [Required]
    public string RadioName { get; set; }

    [Required]
    public string ImageRadio { get; set; }

    [Required]
    public string RadioFile { get; set; }

    [Required]
    public string RadioCountry { get; set; }
}